export const BreadCrumpLabelMap: Record<string, string> = {
  '/assets': 'إدارة الأصول',
  '/assets/categories': 'الفئات',
  '/assets/manufacturers': 'المصنعين',
  '/assets/suppliers': 'الموردين',
  '/assets/contracts': 'العقود',
  '/assets/create': 'إضافة أصل',
  '/assets/equipments': 'إضافة نوع',
  '/facilities/create': 'إضافة مرفق',
  '/facilities': 'المرافق الصحية',
  '/needs': 'طلبات الإحتياج',
  '/map': 'التحليلات المكانية',
  '/home': 'لوحة المعلومات',
  '/inventory': 'عمليات الحصر',
  '/maintenance': 'عمليات الصيانة',
  '/users': 'المستخدمين',
  '/users/create': 'إضافة مستخدم جديد',
  '/needs/create': 'إنشاء طلب إحتياج',
};
